POST http://localhost:3001/api/persons/

Content-Type: 'application/json'

{
    "name": "Jumana KM",
    "number": "34343432"
}


###

GET http://localhost:3001/api/persons/24


###
post http://localhost:3001/api/login
Content-Type: application/json

{
    "username":"aflah03",
    "password":"0000"
}
